# This Exec form will run the Node.js process as PID 1.
# This means that the Node.js process will receive signals from the Docker daemon.

FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y nodejs

WORKDIR /app

COPY index.js .

ENTRYPOINT ["node", "index.js"]